-- Denormalize the event's `kind` onto event_tags so the tag-filter CTE in
-- buildSelectQuery can pre-filter by kind via a covering index. Without
-- this, hot groups whose tag rows are dominated by membership events
-- (NIP-29 kinds 9000/9021) hash-join ~97k tag rows for `h='<group>'`
-- just to throw away ~95% on the kind filter — see issue #23.
--
-- Migration scope is just ADD COLUMN (instant, metadata-only on PG 11+).
-- The matching covering index `(key, value, kind, event_id)` is created
-- by Init() in the post-migrate phase via CREATE INDEX IF NOT EXISTS,
-- which is fast on fresh/dev schemas (empty or tiny event_tags) but on
-- a populated production schema would hold a SHARE lock on event_tags
-- for the duration of the build. The backfill of historical rows is
-- not in this file at all.
--
-- Production rollout therefore expects two one-shot ops via the dbops
-- task BEFORE this code is deployed: a backfill UPDATE setting kind on
-- existing rows, and a CREATE INDEX CONCURRENTLY IF NOT EXISTS for the
-- new covering index. Exact commands are in the PR description for
-- issue #23. Until the backfill is verified complete, the read path
-- emits `kind IN (...) OR kind IS NULL` so un-backfilled rows still
-- match.
ALTER TABLE {{.Name}}__event_tags ADD COLUMN IF NOT EXISTS kind INTEGER;
